---
version: "2.1"
services:
#
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${COREIP} #optional
    volumes:
      - ${LOCVOL1}jellyfin:/config
      - ${MEDIAVOL}:/data
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
    restart: unless-stopped
#
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEXCLAIM}
    volumes:
      - ${LOCVOL1}plex:/config
      - ${MEDIAVOL}:/data
    ports:
      - 32400:32400
      - 3005:3005
      #- 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: unless-stopped
#
#
networks:
  default:
    external:
      name: ${CONNET}